/** Tunable layout parameters — benchmarked via `npm run compare-layouts`. */
export const LAYOUT_PRESETS = {
  baseline: {
    id: 'baseline',
    laborX: -480,
    coalition: { x: 20, y: -40 },
    populistX: 480,
    columnGap: 72,
    minorsMode: 'column-right',
    minorsX: 560,
    minorsTopGap: 120,
    minorsColumnGap: 72,
    donorBaseR: 95,
    donorRingStep: 22,
    donorSpread: 55,
    fitTarget: 'party',
    fitPadding: 40,
    zoomBoost: 1.08,
  },
  wide: {
    id: 'wide',
    laborX: -540,
    coalition: { x: 0, y: -50 },
    populistX: 540,
    columnGap: 84,
    minorsMode: 'column-right',
    minorsX: 620,
    minorsTopGap: 130,
    minorsColumnGap: 76,
    donorBaseR: 108,
    donorRingStep: 24,
    donorSpread: 58,
    fitTarget: 'party',
    fitPadding: 36,
    zoomBoost: 1.12,
  },
  compact: {
    id: 'compact',
    laborX: -400,
    coalition: { x: 10, y: -30 },
    populistX: 400,
    columnGap: 68,
    minorsMode: 'columns-below',
    minorsX: 0,
    minorsTopGap: 110,
    minorsColumnGap: 68,
    donorBaseR: 88,
    donorRingStep: 20,
    donorSpread: 50,
    fitTarget: 'all',
    fitPadding: 44,
    zoomBoost: 1.0,
  },
  spread: {
    id: 'spread',
    laborX: -500,
    coalition: { x: 0, y: -60 },
    populistX: 500,
    columnGap: 80,
    minorsMode: 'row-below',
    minorsX: 0,
    minorsTopGap: 140,
    minorsColumnGap: 56,
    donorBaseR: 100,
    donorRingStep: 22,
    donorSpread: 52,
    fitTarget: 'party',
    fitPadding: 32,
    zoomBoost: 1.15,
  },
  balanced: {
    id: 'balanced',
    laborX: -460,
    coalition: { x: 0, y: -45 },
    populistX: 460,
    columnGap: 76,
    minorsMode: 'columns-below',
    minorsX: 0,
    minorsTopGap: 125,
    minorsColumnGap: 70,
    donorBaseR: 98,
    donorRingStep: 22,
    donorSpread: 54,
    fitTarget: 'party',
    fitPadding: 38,
    zoomBoost: 1.14,
  },
};

export const DEFAULT_LAYOUT_PRESET = 'balanced';

export function getLayoutPreset(id = DEFAULT_LAYOUT_PRESET) {
  return LAYOUT_PRESETS[id] ?? LAYOUT_PRESETS[DEFAULT_LAYOUT_PRESET];
}
